Starting planificador as wwwuser
2014-01-23 11:54:09 [5433] [INFO] Starting gunicorn 18.0
2014-01-23 11:54:09 [5433] [DEBUG] Arbiter booted
2014-01-23 11:54:09 [5433] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/mplanning/run/gunicorn.sock (5433)
2014-01-23 11:54:09 [5433] [INFO] Using worker: sync
2014-01-23 11:54:09 [5444] [INFO] Booting worker with pid: 5444
2014-01-23 11:54:10 [5445] [INFO] Booting worker with pid: 5445
2014-01-23 11:54:10 [5446] [INFO] Booting worker with pid: 5446
2014-01-23 16:12:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:5444)
2014-01-23 16:12:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:5445)
2014-01-23 16:12:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:5446)
2014-01-23 16:12:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:5444)
2014-01-23 16:12:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:5446)
2014-01-23 16:12:42 [7227] [INFO] Booting worker with pid: 7227
2014-01-23 16:12:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:5444)
2014-01-23 16:12:42 [7230] [INFO] Booting worker with pid: 7230
2014-01-23 16:12:42 [7237] [INFO] Booting worker with pid: 7237
2014-01-24 15:02:16 [5433] [CRITICAL] WORKER TIMEOUT (pid:7230)
2014-01-24 15:02:16 [5433] [CRITICAL] WORKER TIMEOUT (pid:7230)
2014-01-24 15:02:16 [9230] [INFO] Booting worker with pid: 9230
2014-01-25 20:48:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:7227)
2014-01-25 20:48:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:7237)
2014-01-25 20:48:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:9230)
2014-01-25 20:48:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:7227)
2014-01-25 20:48:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:7237)
2014-01-25 20:48:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:9230)
2014-01-25 20:48:42 [5433] [CRITICAL] WORKER TIMEOUT (pid:7237)
2014-01-25 20:48:42 [12491] [INFO] Booting worker with pid: 12491
2014-01-25 20:48:42 [12492] [INFO] Booting worker with pid: 12492
2014-01-25 20:48:42 [12501] [INFO] Booting worker with pid: 12501
2014-01-27 08:57:44 [5433] [CRITICAL] WORKER TIMEOUT (pid:12491)
2014-01-27 08:57:44 [5433] [CRITICAL] WORKER TIMEOUT (pid:12492)
2014-01-27 08:57:44 [5433] [CRITICAL] WORKER TIMEOUT (pid:12501)
2014-01-27 08:57:44 [15813] [INFO] Booting worker with pid: 15813
2014-01-27 08:57:44 [15817] [INFO] Booting worker with pid: 15817
2014-01-27 08:57:44 [15822] [INFO] Booting worker with pid: 15822
2014-01-27 11:14:41 [5433] [INFO] Handling signal: term
2014-01-27 11:14:41 [15817] [INFO] Worker exiting (pid: 15817)
2014-01-27 11:14:41 [15813] [INFO] Worker exiting (pid: 15813)
2014-01-27 11:14:41 [15822] [INFO] Worker exiting (pid: 15822)
2014-01-27 11:14:41 [5433] [INFO] Shutting down: Master
Starting planificador as wwwuser
2014-01-27 11:14:43 [19021] [INFO] Starting gunicorn 18.0
2014-01-27 11:14:43 [19021] [DEBUG] Arbiter booted
2014-01-27 11:14:43 [19021] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/run/gunicorn.sock (19021)
2014-01-27 11:14:43 [19021] [INFO] Using worker: sync
2014-01-27 11:14:43 [19032] [INFO] Booting worker with pid: 19032
2014-01-27 11:14:43 [19033] [INFO] Booting worker with pid: 19033
2014-01-27 11:14:43 [19034] [INFO] Booting worker with pid: 19034
2014-01-27 11:20:21 [19032] [DEBUG] GET /
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 11:20:28 [19032] [DEBUG] GET /accounts/login
2014-01-27 11:20:28 [19034] [DEBUG] GET /accounts/login/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 11:20:33 [19034] [DEBUG] POST /accounts/auth/
2014-01-27 11:20:34 [19032] [DEBUG] GET /accounts/loggedin
2014-01-27 11:20:34 [19034] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:20:59 [19033] [DEBUG] GET /planes/plan/list/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 11:21:00 [19032] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 11:23:54 [19034] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:24:08 [19032] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:28:33 [19033] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:28:36 [19034] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:46:05 [19032] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:47:34 [19034] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:47:35 [19033] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:47:36 [19032] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:48:15 [19021] [INFO] Handling signal: term
2014-01-27 11:48:15 [19032] [INFO] Worker exiting (pid: 19032)
2014-01-27 11:48:15 [19033] [INFO] Worker exiting (pid: 19033)
2014-01-27 11:48:15 [19034] [INFO] Worker exiting (pid: 19034)
2014-01-27 11:48:15 [19021] [INFO] Shutting down: Master
Starting planificador as wwwuser
2014-01-27 11:48:16 [19820] [INFO] Starting gunicorn 18.0
2014-01-27 11:48:16 [19820] [DEBUG] Arbiter booted
2014-01-27 11:48:16 [19820] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/run/gunicorn.sock (19820)
2014-01-27 11:48:16 [19820] [INFO] Using worker: sync
2014-01-27 11:48:16 [19831] [INFO] Booting worker with pid: 19831
2014-01-27 11:48:16 [19832] [INFO] Booting worker with pid: 19832
2014-01-27 11:48:16 [19833] [INFO] Booting worker with pid: 19833
2014-01-27 11:48:19 [19831] [DEBUG] GET /accounts/loggedin/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 11:48:19 [19833] [DEBUG] GET /accounts/loggedin/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 11:49:02 [19833] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:49:03 [19831] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:49:04 [19832] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:49:04 [19832] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 11:49:37 [19833] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:49:38 [19832] [DEBUG] GET /accounts/loggedin/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 11:49:46 [19832] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:49:47 [19833] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:50:02 [19833] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:50:03 [19832] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:50:06 [19832] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:50:06 [19833] [DEBUG] GET /accounts/loggedin/
2014-01-27 11:50:08 [19831] [DEBUG] GET /planes/plan/list/
2014-01-27 11:50:15 [19820] [INFO] Handling signal: term
2014-01-27 11:50:15 [19833] [INFO] Worker exiting (pid: 19833)
2014-01-27 11:50:15 [19832] [INFO] Worker exiting (pid: 19832)
2014-01-27 11:50:15 [19831] [INFO] Worker exiting (pid: 19831)
2014-01-27 11:50:15 [19820] [INFO] Shutting down: Master
Starting planificador as wwwuser
2014-01-27 11:50:16 [19903] [INFO] Starting gunicorn 18.0
2014-01-27 11:50:16 [19903] [DEBUG] Arbiter booted
2014-01-27 11:50:16 [19903] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/run/gunicorn.sock (19903)
2014-01-27 11:50:16 [19903] [INFO] Using worker: sync
2014-01-27 11:50:16 [19914] [INFO] Booting worker with pid: 19914
2014-01-27 11:50:16 [19915] [INFO] Booting worker with pid: 19915
2014-01-27 11:50:16 [19916] [INFO] Booting worker with pid: 19916
2014-01-27 11:50:21 [19916] [DEBUG] GET /planes/plan/list/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 11:50:23 [19915] [DEBUG] GET /planes/plan/list/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 11:50:24 [19914] [DEBUG] GET /accounts/loggedin/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 11:58:38 [19916] [DEBUG] GET /accounts/loggedin/
2014-01-27 12:00:41 [19914] [DEBUG] GET /accounts/loggedin/
2014-01-27 12:00:48 [19915] [DEBUG] GET /planes/plan/list/
2014-01-27 12:00:49 [19916] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 12:00:50 [19915] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 12:00:51 [19915] [DEBUG] GET /categorias/item/nodesearch/
/home/rcanepa/Development/planificador/mplanning/categorias/views.py:106: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  categoria__organizacion=self.request.user.get_profile().organizacion)

/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/http/response.py:330: DeprecationWarning: Using mimetype keyword argument is deprecated, use content_type instead
  super(HttpResponse, self).__init__(*args, **kwargs)

2014-01-27 12:00:53 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:00:54 [19914] [DEBUG] GET /categorias/item/nodesearch/
/home/rcanepa/Development/planificador/mplanning/categorias/views.py:106: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  categoria__organizacion=self.request.user.get_profile().organizacion)

/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/http/response.py:330: DeprecationWarning: Using mimetype keyword argument is deprecated, use content_type instead
  super(HttpResponse, self).__init__(*args, **kwargs)

2014-01-27 12:00:55 [19916] [DEBUG] GET /categorias/item/nodesearch/
/home/rcanepa/Development/planificador/mplanning/categorias/views.py:106: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  categoria__organizacion=self.request.user.get_profile().organizacion)

/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/http/response.py:330: DeprecationWarning: Using mimetype keyword argument is deprecated, use content_type instead
  super(HttpResponse, self).__init__(*args, **kwargs)

2014-01-27 12:02:09 [19915] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 12:02:10 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:12 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:13 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:13 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:22 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:22 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:22 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:22 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:22 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:22 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:22 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:22 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:22 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:22 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:23 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:24 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:24 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:24 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:24 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:24 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:24 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:02:27 [19914] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 12:02:28 [19916] [DEBUG] GET /planes/plan/stage2/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:208: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:211: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:226: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 12:02:29 [19916] [DEBUG] GET /planes/plan/proystats/
2014-01-27 12:02:29 [19916] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 12:02:30 [19916] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 12:02:32 [19916] [DEBUG] GET /planes/plan/itemplanventasearch/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:404: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  controlventa = Controlventa.objects.filter(organizacion=self.request.user.get_profile().organizacion).latest('fecha_creacion')

2014-01-27 12:02:35 [19914] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:02:37 [19914] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:02:39 [19914] [DEBUG] GET /planes/plan/itemplancompventasearch/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:572: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  controlventa = Controlventa.objects.filter(organizacion=self.request.user.get_profile().organizacion).latest('fecha_creacion')

2014-01-27 12:03:02 [19914] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 12:03:03 [19914] [DEBUG] GET /planes/plan/stage3/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:734: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:744: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:757: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 12:03:03 [19914] [DEBUG] GET /planes/plan/planstats/
2014-01-27 12:03:05 [19915] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 12:03:06 [19916] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 12:03:07 [19915] [DEBUG] GET /planes/plan/itemplanventatemp/
2014-01-27 12:03:10 [19916] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:03:11 [19915] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:03:12 [19914] [DEBUG] GET /planes/plan/itemplanventatempcomp/
2014-01-27 12:03:26 [19915] [DEBUG] GET /planes/plan/list/
2014-01-27 12:03:27 [19916] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 12:03:28 [19915] [DEBUG] GET /planes/plan/resumen/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:1157: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:1171: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 12:03:30 [19914] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:03:31 [19915] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:03:31 [19916] [DEBUG] GET /planes/plan/resumendata/
2014-01-27 12:04:01 [19915] [DEBUG] GET /accounts/login
2014-01-27 12:04:01 [19915] [DEBUG] GET /accounts/login/
2014-01-27 12:04:07 [19915] [DEBUG] POST /accounts/auth/
2014-01-27 12:04:07 [19916] [DEBUG] GET /accounts/loggedin
2014-01-27 12:04:07 [19914] [DEBUG] GET /accounts/loggedin/
2014-01-27 12:04:09 [19914] [DEBUG] GET /planes/plan/list/
2014-01-27 12:04:11 [19914] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 12:04:13 [19916] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 12:04:14 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:04:15 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:04:16 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:04:17 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 12:04:24 [19914] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 12:04:26 [19916] [DEBUG] GET /planes/plan/stage2/18/
2014-01-27 12:04:26 [19914] [DEBUG] GET /planes/plan/proystats/
2014-01-27 12:04:28 [19914] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 12:04:29 [19914] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 12:04:30 [19916] [DEBUG] GET /planes/plan/itemplanventasearch/
2014-01-27 12:04:38 [19914] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:04:40 [19914] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:04:41 [19915] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:04:43 [19914] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:04:46 [19914] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:04:47 [19914] [DEBUG] GET /planes/plan/itemplancompventasearch/
2014-01-27 12:04:51 [19915] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 12:04:52 [19916] [DEBUG] GET /planes/plan/stage3/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:734: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:744: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:757: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 12:04:53 [19914] [DEBUG] GET /planes/plan/planstats/
2014-01-27 12:04:54 [19915] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 12:04:55 [19915] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 12:04:56 [19914] [DEBUG] GET /planes/plan/itemplanventatemp/
2014-01-27 12:04:58 [19916] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:05:01 [19915] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:05:02 [19916] [DEBUG] GET /planes/plan/itemplanventatempcomp/
2014-01-27 12:05:18 [19916] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 12:05:20 [19915] [DEBUG] GET /planes/plan/resumen/18/
2014-01-27 12:05:23 [19914] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:05:23 [19914] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 12:05:24 [19916] [DEBUG] GET /planes/plan/resumendata/
2014-01-27 13:34:02 [19916] [DEBUG] GET /planes/plan/resumen/18/
2014-01-27 13:34:02 [19916] [DEBUG] GET /accounts/login/
2014-01-27 13:34:04 [19915] [DEBUG] POST /accounts/auth/
2014-01-27 13:34:04 [19914] [DEBUG] GET /accounts/loggedin
2014-01-27 13:34:04 [19914] [DEBUG] GET /accounts/loggedin/
2014-01-27 13:34:27 [19914] [DEBUG] GET /accounts/loggedin/
2014-01-27 13:34:29 [19916] [DEBUG] GET /accounts/logout/
2014-01-27 13:34:30 [19914] [DEBUG] GET /accounts/login/
2014-01-27 13:34:31 [19915] [DEBUG] POST /accounts/auth/
2014-01-27 13:34:31 [19915] [DEBUG] GET /accounts/loggedin
2014-01-27 13:34:31 [19915] [DEBUG] GET /accounts/loggedin/
2014-01-27 13:34:33 [19916] [DEBUG] GET /planes/plan/list/
2014-01-27 13:34:34 [19916] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 13:34:36 [19916] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 13:34:39 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:40 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:41 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:42 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:47 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:47 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:47 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:48 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:48 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:48 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:48 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:48 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:48 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:48 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:48 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:49 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19914] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19916] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 13:34:50 [19915] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 14:31:45 [19915] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 14:31:48 [19915] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 14:31:50 [19914] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 14:31:51 [19914] [DEBUG] GET /planes/plan/stage2/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:208: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:211: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:226: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 14:31:51 [19916] [DEBUG] GET /planes/plan/proystats/
2014-01-27 14:31:52 [19915] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 14:31:53 [19915] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 14:31:55 [19914] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 14:31:59 [19914] [DEBUG] GET /planes/plan/resumen/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:1157: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:1171: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 14:32:00 [19916] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 15:32:03 [19914] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 15:32:03 [19914] [DEBUG] GET /accounts/login/
2014-01-27 15:32:05 [19916] [DEBUG] POST /accounts/auth/
2014-01-27 15:32:05 [19915] [DEBUG] GET /accounts/loggedin
2014-01-27 15:32:05 [19915] [DEBUG] GET /accounts/loggedin/
2014-01-27 15:32:06 [19915] [DEBUG] GET /planes/plan/list/
2014-01-27 15:32:07 [19914] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 15:32:08 [19916] [DEBUG] GET /planes/plan/stage2/18/
2014-01-27 15:32:08 [19915] [DEBUG] GET /planes/plan/proystats/
2014-01-27 15:32:10 [19914] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 15:32:11 [19915] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 15:32:12 [19914] [DEBUG] GET /planes/plan/itemplanventasearch/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:404: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  controlventa = Controlventa.objects.filter(organizacion=self.request.user.get_profile().organizacion).latest('fecha_creacion')

2014-01-27 15:32:16 [19915] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 15:32:18 [19916] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 15:32:19 [19915] [DEBUG] GET /planes/plan/itemplancompventasearch/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:572: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  controlventa = Controlventa.objects.filter(organizacion=self.request.user.get_profile().organizacion).latest('fecha_creacion')

2014-01-27 15:55:15 [19916] [DEBUG] GET /planes/plan/itemplancompventasearch/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:572: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  controlventa = Controlventa.objects.filter(organizacion=self.request.user.get_profile().organizacion).latest('fecha_creacion')

2014-01-27 15:55:16 [19914] [DEBUG] GET /planes/plan/list/
2014-01-27 15:55:17 [19915] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 15:55:18 [19914] [DEBUG] GET /planes/plan/resumen/18/
2014-01-27 16:00:59 [19903] [INFO] Handling signal: term
2014-01-27 16:00:59 [19914] [INFO] Worker exiting (pid: 19914)
2014-01-27 16:00:59 [19915] [INFO] Worker exiting (pid: 19915)
2014-01-27 16:00:59 [19916] [INFO] Worker exiting (pid: 19916)
2014-01-27 16:00:59 [19903] [INFO] Shutting down: Master
Starting planificador as wwwuser
2014-01-27 16:02:05 [1429] [INFO] Starting gunicorn 18.0
2014-01-27 16:02:05 [1429] [DEBUG] Arbiter booted
2014-01-27 16:02:05 [1429] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/run/gunicorn.sock (1429)
2014-01-27 16:02:05 [1429] [INFO] Using worker: sync
2014-01-27 16:02:05 [1699] [INFO] Booting worker with pid: 1699
2014-01-27 16:02:05 [1700] [INFO] Booting worker with pid: 1700
2014-01-27 16:02:05 [1707] [INFO] Booting worker with pid: 1707
2014-01-27 16:03:06 [1700] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:03:06 [1700] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:19 [1707] [DEBUG] GET /
2014-01-27 16:03:19 [1707] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:21 [1699] [DEBUG] GET /accounts/login
2014-01-27 16:03:21 [1699] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:24 [1700] [DEBUG] GET /accounts/login
2014-01-27 16:03:24 [1700] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:25 [1699] [DEBUG] GET /accounts/login
2014-01-27 16:03:25 [1699] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:25 [1700] [DEBUG] GET /accounts/login
2014-01-27 16:03:25 [1700] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:25 [1700] [DEBUG] GET /accounts/login
2014-01-27 16:03:25 [1700] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:26 [1699] [DEBUG] GET /accounts/login
2014-01-27 16:03:26 [1699] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:26 [1707] [DEBUG] GET /accounts/login
2014-01-27 16:03:26 [1707] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:27 [1707] [DEBUG] GET /accounts/login
2014-01-27 16:03:27 [1707] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:28 [1699] [DEBUG] GET /accounts/login
2014-01-27 16:03:28 [1699] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:29 [1699] [DEBUG] GET /accounts/login
2014-01-27 16:03:29 [1699] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:55 [1699] [DEBUG] GET /accounts/login
2014-01-27 16:03:55 [1699] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:55 [1700] [DEBUG] GET /accounts/login
2014-01-27 16:03:55 [1700] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:55 [1700] [DEBUG] GET /accounts/login
2014-01-27 16:03:55 [1700] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:56 [1700] [DEBUG] GET /accounts/login
2014-01-27 16:03:56 [1700] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:56 [1700] [DEBUG] GET /accounts/login
2014-01-27 16:03:56 [1700] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:56 [1699] [DEBUG] GET /accounts/login
2014-01-27 16:03:56 [1699] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:03:56 [1699] [DEBUG] GET /accounts/login
2014-01-27 16:03:56 [1699] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 66, in <module>
    STATIC_ROOT = os.path.join(PROJECT_DIRECTORY,'static/')
NameError: name 'PROJECT_DIRECTORY' is not defined
2014-01-27 16:05:51 [1707] [DEBUG] GET /
2014-01-27 16:05:52 [1699] [DEBUG] GET /
2014-01-27 16:05:52 [1700] [DEBUG] GET /
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 16:05:53 [1700] [DEBUG] Ignoring EPIPE
2014-01-27 16:05:53 [1700] [DEBUG] GET /
2014-01-27 16:05:53 [1707] [DEBUG] Ignoring EPIPE
2014-01-27 16:05:53 [1707] [DEBUG] GET /
2014-01-27 16:05:53 [1699] [DEBUG] Ignoring EPIPE
2014-01-27 16:05:53 [1699] [DEBUG] GET /
2014-01-27 16:05:53 [1700] [DEBUG] Ignoring EPIPE
2014-01-27 16:05:53 [1700] [DEBUG] GET /
2014-01-27 16:05:53 [1707] [DEBUG] Ignoring EPIPE
2014-01-27 16:05:53 [1699] [DEBUG] Ignoring EPIPE
2014-01-27 16:05:55 [1700] [DEBUG] GET /
2014-01-27 16:05:57 [1707] [DEBUG] GET /accounts/login
2014-01-27 16:05:57 [1699] [DEBUG] GET /accounts/login/
2014-01-27 16:05:59 [1699] [DEBUG] POST /accounts/auth/
2014-01-27 16:06:00 [1699] [DEBUG] GET /accounts/loggedin
2014-01-27 16:06:00 [1707] [DEBUG] GET /accounts/loggedin/
2014-01-27 16:06:01 [1700] [DEBUG] GET /planes/plan/list/
2014-01-27 16:06:03 [1699] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:06:04 [1707] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 16:06:06 [1700] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:06:07 [1700] [DEBUG] GET /planes/plan/stage2/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:208: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:211: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:226: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 16:06:08 [1699] [DEBUG] GET /planes/plan/proystats/
/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/http/response.py:330: DeprecationWarning: Using mimetype keyword argument is deprecated, use content_type instead
  super(HttpResponse, self).__init__(*args, **kwargs)

2014-01-27 16:06:09 [1707] [DEBUG] GET /planes/plan/categoriasearchlist/
/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/http/response.py:330: DeprecationWarning: Using mimetype keyword argument is deprecated, use content_type instead
  super(HttpResponse, self).__init__(*args, **kwargs)

2014-01-27 16:06:10 [1699] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 16:06:11 [1699] [DEBUG] GET /planes/plan/itemplanventasearch/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:404: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  controlventa = Controlventa.objects.filter(organizacion=self.request.user.get_profile().organizacion).latest('fecha_creacion')

2014-01-27 16:06:12 [1707] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:06:14 [1699] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:06:15 [1699] [DEBUG] GET /planes/plan/itemplancompventasearch/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:572: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  controlventa = Controlventa.objects.filter(organizacion=self.request.user.get_profile().organizacion).latest('fecha_creacion')

2014-01-27 16:06:23 [1707] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:06:24 [1700] [DEBUG] GET /planes/plan/stage3/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:734: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:744: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:757: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 16:06:24 [1699] [DEBUG] GET /planes/plan/planstats/
2014-01-27 16:06:25 [1699] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 16:06:26 [1707] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 16:06:27 [1707] [DEBUG] GET /planes/plan/itemplanventatemp/
2014-01-27 16:06:29 [1707] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:06:31 [1700] [DEBUG] GET /planes/plan/categoriacompsearchlist/
/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/http/response.py:330: DeprecationWarning: Using mimetype keyword argument is deprecated, use content_type instead
  super(HttpResponse, self).__init__(*args, **kwargs)

2014-01-27 16:06:32 [1707] [DEBUG] GET /planes/plan/itemplanventatempcomp/
2014-01-27 16:08:44 [1707] [DEBUG] GET /planes/plan/stage3/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:734: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:744: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:757: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 16:08:45 [1700] [DEBUG] GET /planes/plan/planstats/
2014-01-27 16:08:46 [1707] [DEBUG] GET /accounts/loggedin/
2014-01-27 16:08:48 [1699] [DEBUG] GET /accounts/logout/
2014-01-27 16:08:49 [1700] [DEBUG] GET /accounts/login/
2014-01-27 16:08:50 [1707] [DEBUG] POST /accounts/auth/
2014-01-27 16:08:50 [1707] [DEBUG] GET /accounts/loggedin
2014-01-27 16:08:50 [1707] [DEBUG] GET /accounts/loggedin/
2014-01-27 16:09:11 [1707] [DEBUG] GET /accounts/loggedin/
2014-01-27 16:09:12 [1699] [DEBUG] GET /planes/plan/list/
2014-01-27 16:09:13 [1707] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:09:23 [1429] [INFO] Handling signal: term
2014-01-27 16:09:23 [1699] [INFO] Worker exiting (pid: 1699)
2014-01-27 16:09:23 [1707] [INFO] Worker exiting (pid: 1707)
2014-01-27 16:09:23 [1700] [INFO] Worker exiting (pid: 1700)
2014-01-27 16:09:23 [1429] [INFO] Shutting down: Master
Starting planificador as wwwuser
2014-01-27 16:09:25 [2658] [INFO] Starting gunicorn 18.0
2014-01-27 16:09:25 [2658] [DEBUG] Arbiter booted
2014-01-27 16:09:25 [2658] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/run/gunicorn.sock (2658)
2014-01-27 16:09:25 [2658] [INFO] Using worker: sync
2014-01-27 16:09:25 [2669] [INFO] Booting worker with pid: 2669
2014-01-27 16:09:25 [2670] [INFO] Booting worker with pid: 2670
2014-01-27 16:09:25 [2671] [INFO] Booting worker with pid: 2671
2014-01-27 16:09:38 [2671] [DEBUG] GET /planes/plan/detail/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 16:09:40 [2670] [DEBUG] GET /accounts/loggedin/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 16:09:41 [2669] [DEBUG] GET /planes/plan/list/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 16:09:42 [2671] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:09:44 [2671] [DEBUG] GET /planes/plan/resumen/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:1157: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:1171: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 16:09:47 [2670] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:10:48 [2658] [INFO] Handling signal: term
2014-01-27 16:10:48 [2670] [INFO] Worker exiting (pid: 2670)
2014-01-27 16:10:48 [2669] [INFO] Worker exiting (pid: 2669)
2014-01-27 16:10:48 [2671] [INFO] Worker exiting (pid: 2671)
2014-01-27 16:10:48 [2658] [INFO] Shutting down: Master
Starting planificador as wwwuser
2014-01-27 16:10:49 [2718] [INFO] Starting gunicorn 18.0
2014-01-27 16:10:49 [2718] [DEBUG] Arbiter booted
2014-01-27 16:10:49 [2718] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/run/gunicorn.sock (2718)
2014-01-27 16:10:49 [2718] [INFO] Using worker: sync
2014-01-27 16:10:49 [2729] [INFO] Booting worker with pid: 2729
2014-01-27 16:10:49 [2730] [INFO] Booting worker with pid: 2730
2014-01-27 16:10:49 [2731] [INFO] Booting worker with pid: 2731
2014-01-27 16:10:55 [2729] [DEBUG] GET /planes/plan/detail/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:10:59 [2731] [DEBUG] GET /planes/plan/detail/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:12:40 [2730] [DEBUG] GET /planes/plan/detail/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:12:42 [2729] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:12:45 [2718] [INFO] Handling signal: term
2014-01-27 16:12:45 [2729] [INFO] Worker exiting (pid: 2729)
2014-01-27 16:12:45 [2731] [INFO] Worker exiting (pid: 2731)
2014-01-27 16:12:45 [2730] [INFO] Worker exiting (pid: 2730)
2014-01-27 16:12:45 [2718] [INFO] Shutting down: Master
Starting planificador as wwwuser
2014-01-27 16:12:46 [2777] [INFO] Starting gunicorn 18.0
2014-01-27 16:12:46 [2777] [DEBUG] Arbiter booted
2014-01-27 16:12:46 [2777] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/run/gunicorn.sock (2777)
2014-01-27 16:12:46 [2777] [INFO] Using worker: sync
2014-01-27 16:12:46 [2788] [INFO] Booting worker with pid: 2788
2014-01-27 16:12:46 [2789] [INFO] Booting worker with pid: 2789
2014-01-27 16:12:46 [2790] [INFO] Booting worker with pid: 2790
2014-01-27 16:12:52 [2789] [DEBUG] GET /planes/plan/detail/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:12:53 [2788] [DEBUG] GET /planes/plan/detail/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:12:56 [2788] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:13:56 [2790] [DEBUG] GET /accounts/loggedin/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:14:10 [2789] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:14:57 [2788] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:14:59 [2788] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:14:59 [2789] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:15:05 [2790] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:15:06 [2790] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:15:06 [2789] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:15:09 [2788] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:17:36 [2788] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:08 [2788] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:09 [2790] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:10 [2789] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:10 [2789] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:11 [2790] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:12 [2789] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:12 [2788] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:13 [2789] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:14 [2790] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:17 [2777] [INFO] Handling signal: term
2014-01-27 16:18:17 [2789] [INFO] Worker exiting (pid: 2789)
2014-01-27 16:18:17 [2788] [INFO] Worker exiting (pid: 2788)
2014-01-27 16:18:17 [2790] [INFO] Worker exiting (pid: 2790)
2014-01-27 16:18:17 [2777] [INFO] Shutting down: Master
Starting planificador as wwwuser
2014-01-27 16:18:18 [2917] [INFO] Starting gunicorn 18.0
2014-01-27 16:18:18 [2917] [DEBUG] Arbiter booted
2014-01-27 16:18:18 [2917] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/run/gunicorn.sock (2917)
2014-01-27 16:18:18 [2917] [INFO] Using worker: sync
2014-01-27 16:18:18 [2928] [INFO] Booting worker with pid: 2928
2014-01-27 16:18:18 [2929] [INFO] Booting worker with pid: 2929
2014-01-27 16:18:18 [2930] [INFO] Booting worker with pid: 2930
2014-01-27 16:18:22 [2930] [DEBUG] GET /planes/plan/detail/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:24 [2929] [DEBUG] GET /planes/plan/detail/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:18:26 [2930] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:19:31 [2928] [DEBUG] GET /accounts/loggedin/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:32 [2928] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:33 [2930] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:34 [2929] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:35 [2930] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:36 [2929] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:37 [2929] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:38 [2930] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:39 [2929] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:40 [2928] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:40 [2928] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:41 [2930] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:45 [2917] [INFO] Handling signal: term
2014-01-27 16:19:45 [2929] [INFO] Worker exiting (pid: 2929)
2014-01-27 16:19:45 [2928] [INFO] Worker exiting (pid: 2928)
2014-01-27 16:19:45 [2930] [INFO] Worker exiting (pid: 2930)
2014-01-27 16:19:45 [2917] [INFO] Shutting down: Master
Starting planificador as wwwuser
2014-01-27 16:19:46 [2988] [INFO] Starting gunicorn 18.0
2014-01-27 16:19:46 [2988] [DEBUG] Arbiter booted
2014-01-27 16:19:46 [2988] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/run/gunicorn.sock (2988)
2014-01-27 16:19:46 [2988] [INFO] Using worker: sync
2014-01-27 16:19:46 [2999] [INFO] Booting worker with pid: 2999
2014-01-27 16:19:46 [3000] [INFO] Booting worker with pid: 3000
2014-01-27 16:19:46 [3001] [INFO] Booting worker with pid: 3001
2014-01-27 16:19:50 [2999] [DEBUG] GET /accounts/loggedin/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:51 [3001] [DEBUG] GET /accounts/loggedin/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:19:52 [2999] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:20:44 [3001] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:20:46 [3000] [DEBUG] GET /planes/plan/list/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Internal Server Error: /planes/plan/list/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:20:47 [3000] [DEBUG] GET /planes/plan/stage2/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:208: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:211: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:226: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

Internal Server Error: /planes/plan/stage2/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:20:48 [2999] [DEBUG] GET /planes/plan/detail/18/
Internal Server Error: /planes/plan/detail/18/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:20:49 [3001] [DEBUG] GET /planes/plan/list/
Internal Server Error: /planes/plan/list/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: base.html
2014-01-27 16:20:49 [3000] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:20:51 [2999] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:22:27 [2999] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:22:42 [3001] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:23 [3000] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:24 [3000] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:25 [3000] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:25 [2999] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:26 [3001] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:26 [2999] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:27 [2999] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:27 [3000] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:28 [3001] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:28 [2999] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:28 [3000] [DEBUG] GET /accounts/loggedin/
Internal Server Error: /accounts/loggedin/
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: loggedin.html
2014-01-27 16:23:40 [2988] [INFO] Handling signal: term
2014-01-27 16:23:40 [3000] [INFO] Worker exiting (pid: 3000)
2014-01-27 16:23:40 [3001] [INFO] Worker exiting (pid: 3001)
2014-01-27 16:23:40 [2999] [INFO] Worker exiting (pid: 2999)
2014-01-27 16:23:40 [2988] [INFO] Shutting down: Master
Starting planificador as wwwuser
2014-01-27 16:23:41 [3217] [INFO] Starting gunicorn 18.0
2014-01-27 16:23:41 [3217] [DEBUG] Arbiter booted
2014-01-27 16:23:41 [3217] [INFO] Listening at: unix:/home/rcanepa/Development/planificador/run/gunicorn.sock (3217)
2014-01-27 16:23:41 [3217] [INFO] Using worker: sync
2014-01-27 16:23:41 [3228] [INFO] Booting worker with pid: 3228
2014-01-27 16:23:41 [3229] [INFO] Booting worker with pid: 3229
2014-01-27 16:23:41 [3230] [INFO] Booting worker with pid: 3230
2014-01-27 16:23:46 [3230] [DEBUG] GET /accounts/loggedin/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 16:28:46 [3229] [DEBUG] GET /accounts/loggedin/
2014-01-27 16:28:46 [3229] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 132
    os.path.join(TEMP_PATH, 'templates')
     ^
SyntaxError: invalid syntax
2014-01-27 16:28:47 [3230] [DEBUG] GET /accounts/loggedin/
2014-01-27 16:28:49 [3228] [DEBUG] GET /planes/plan/list/
2014-01-27 16:28:49 [3228] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 132
    os.path.join(TEMP_PATH, 'templates')
     ^
SyntaxError: invalid syntax
2014-01-27 16:28:50 [3230] [DEBUG] GET /planes/plan/list/
2014-01-27 16:28:52 [3230] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:28:53 [3228] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 16:28:53 [3228] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/rcanepa/Development/planificador/mplanning/planificador/settings.py", line 132
    os.path.join(TEMP_PATH, 'templates')
     ^
SyntaxError: invalid syntax
2014-01-27 16:29:12 [3229] [DEBUG] GET /planes/plan/stage1/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 16:29:13 [3228] [DEBUG] GET /planes/plan/stage1/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:14: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

2014-01-27 16:29:15 [3228] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:29:20 [3229] [DEBUG] GET /planes/plan/list/
2014-01-27 16:29:21 [3228] [DEBUG] GET /administracion/index/
2014-01-27 16:29:23 [3230] [DEBUG] GET /administracion/index/
2014-01-27 16:29:24 [3229] [DEBUG] GET /categorias/cat/list/
/home/rcanepa/Development/planificador/mplanning/categorias/views.py:39: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  organizacion=self.request.user.get_profile().organizacion)

2014-01-27 16:29:26 [3230] [DEBUG] GET /administracion/index/
2014-01-27 16:29:26 [3228] [DEBUG] GET /categorias/item/list/
2014-01-27 16:29:27 [3228] [DEBUG] GET /categorias/item/nodesearch/
/home/rcanepa/Development/planificador/mplanning/categorias/views.py:106: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  categoria__organizacion=self.request.user.get_profile().organizacion)

/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/http/response.py:330: DeprecationWarning: Using mimetype keyword argument is deprecated, use content_type instead
  super(HttpResponse, self).__init__(*args, **kwargs)

2014-01-27 16:29:28 [3230] [DEBUG] GET /categorias/item/nodesearch/
/home/rcanepa/Development/planificador/mplanning/categorias/views.py:106: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  categoria__organizacion=self.request.user.get_profile().organizacion)

/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/http/response.py:330: DeprecationWarning: Using mimetype keyword argument is deprecated, use content_type instead
  super(HttpResponse, self).__init__(*args, **kwargs)

2014-01-27 16:29:29 [3229] [DEBUG] GET /categorias/item/nodesearch/
/home/rcanepa/Development/planificador/mplanning/categorias/views.py:106: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  categoria__organizacion=self.request.user.get_profile().organizacion)

/home/rcanepa/.virtualenvs/plan/local/lib/python2.7/site-packages/django/http/response.py:330: DeprecationWarning: Using mimetype keyword argument is deprecated, use content_type instead
  super(HttpResponse, self).__init__(*args, **kwargs)

2014-01-27 16:29:31 [3230] [DEBUG] GET /administracion/index/
2014-01-27 16:29:32 [3229] [DEBUG] GET /planes/temporada/list/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:35: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  return Temporada.objects.filter(organizacion=self.request.user.get_profile().organizacion)

2014-01-27 16:29:33 [3228] [DEBUG] GET /planes/temporada/detail/3/
2014-01-27 16:29:35 [3228] [DEBUG] GET /administracion/index/
2014-01-27 16:29:36 [3229] [DEBUG] GET /calendarios/calendario/list/
/home/rcanepa/Development/planificador/mplanning/calendarios/views.py:18: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  return Calendario.objects.filter(organizacion=self.request.user.get_profile().organizacion)

2014-01-27 16:29:39 [3230] [DEBUG] GET /administracion/index/
2014-01-27 16:29:40 [3228] [DEBUG] GET /ventas/controlventa/list/
/home/rcanepa/Development/planificador/mplanning/ventas/views.py:22: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  return Controlventa.objects.filter(organizacion=self.request.user.get_profile().organizacion)

2014-01-27 16:29:41 [3230] [DEBUG] GET /ventas/controlventa/detail/1/
2014-01-27 16:29:43 [3228] [DEBUG] GET /accounts/loggedin/
2014-01-27 16:29:44 [3228] [DEBUG] GET /planes/plan/list/
2014-01-27 16:29:46 [3228] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:29:47 [3229] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 16:29:50 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:51 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:29:52 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:30:57 [3230] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:30:58 [3228] [DEBUG] GET /planes/plan/stage2/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:208: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:211: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:226: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 16:30:59 [3230] [DEBUG] GET /planes/plan/proystats/
2014-01-27 16:31:01 [3228] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:31:01 [3229] [DEBUG] GET /planes/plan/stage1/18/
2014-01-27 16:31:02 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:03 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:03 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:03 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:03 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:03 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:03 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:03 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:03 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:03 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3228] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:04 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:05 [3230] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:05 [3229] [DEBUG] GET /categorias/item/nodesearch/
2014-01-27 16:31:06 [3229] [DEBUG] POST /planes/plan/savestage1/
2014-01-27 16:31:07 [3228] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:31:08 [3230] [DEBUG] GET /planes/plan/stage2/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:208: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:211: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:226: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 16:31:09 [3228] [DEBUG] GET /planes/plan/proystats/
2014-01-27 16:31:10 [3228] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 16:31:11 [3229] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 16:31:23 [3230] [DEBUG] GET /planes/plan/itemplanventasearch/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:404: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  controlventa = Controlventa.objects.filter(organizacion=self.request.user.get_profile().organizacion).latest('fecha_creacion')

2014-01-27 16:31:26 [3229] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:31:27 [3230] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:31:27 [3230] [DEBUG] GET /planes/plan/itemplancompventasearch/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:572: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  controlventa = Controlventa.objects.filter(organizacion=self.request.user.get_profile().organizacion).latest('fecha_creacion')

2014-01-27 16:31:35 [3229] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:31:36 [3228] [DEBUG] GET /planes/plan/stage3/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:734: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:744: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(Q(categoria_padre=None) | Q(planificable=True))

/home/rcanepa/Development/planificador/mplanning/planes/views.py:757: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 16:31:36 [3228] [DEBUG] GET /planes/plan/planstats/
2014-01-27 16:31:37 [3228] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 16:31:38 [3230] [DEBUG] GET /planes/plan/categoriasearchlist/
2014-01-27 16:31:53 [3229] [DEBUG] GET /planes/plan/itemplanventatemp/
2014-01-27 16:31:57 [3230] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:31:58 [3228] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:31:59 [3230] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:31:59 [3229] [DEBUG] GET /planes/plan/itemplanventatempcomp/
2014-01-27 16:32:24 [3230] [DEBUG] GET /planes/plan/detail/18/
2014-01-27 16:32:25 [3229] [DEBUG] GET /planes/plan/resumen/18/
/home/rcanepa/Development/planificador/mplanning/planes/views.py:1157: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  combo_categorias_comp = Categoria.objects.filter(organizacion=self.request.user.get_profile().organizacion).exclude(categoria_padre=None)

/home/rcanepa/Development/planificador/mplanning/planes/views.py:1171: DeprecationWarning: The use of AUTH_PROFILE_MODULE to define user profiles has been deprecated.
  items_categoria_raiz = self.request.user.get_profile().items_visibles(categoria_raiz)

2014-01-27 16:32:28 [3229] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:32:29 [3229] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:32:30 [3229] [DEBUG] GET /planes/plan/resumendata/
2014-01-27 16:32:40 [3228] [DEBUG] GET /planes/plan/categoriacompsearchlist/
2014-01-27 16:32:41 [3230] [DEBUG] GET /planes/plan/resumendata/
